In [1]:
import torch

In [10]:
out_logits = torch.tensor([[0.1, 0.9],[0.8, 0.2]])
targets = torch.tensor([0, 1])
targets.shape

torch.Size([2])

In [11]:
targets.unsqueeze(-1)

tensor([[0],
        [1]])

In [12]:
out_logits.gather(dim=-1, index=targets.unsqueeze(-1))

tensor([[0.1000],
        [0.2000]])

In [13]:
logsumexp = torch.logsumexp(input=out_logits, dim=-1, keepdim=True)
logsumexp

tensor([[1.2711],
        [1.2375]])

In [1]:
import torch

In [4]:
N, context_length, batch_size = 100, 16, 8
starts = torch.randint(0, N - context_length, (batch_size,))
starts

tensor([52, 22, 26, 30, 37, 83, 72, 10])

In [9]:
starts[:, None].shape

torch.Size([8, 1])

In [10]:
offsets = torch.arange(context_length)
offsets.shape

torch.Size([16])

In [12]:
offsets[None, :]

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [7]:
idx = starts[:, None] + offsets[None, :]
idx

tensor([[52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67],
        [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37],
        [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
        [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52],
        [83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98],
        [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]])