In [1]:
import torch

In [10]:
out_logits = torch.tensor([[0.1, 0.9],[0.8, 0.2]])
targets = torch.tensor([0, 1])
targets.shape

torch.Size([2])

In [11]:
targets.unsqueeze(-1)

tensor([[0],
        [1]])

In [12]:
out_logits.gather(dim=-1, index=targets.unsqueeze(-1))

tensor([[0.1000],
        [0.2000]])

In [13]:
logsumexp = torch.logsumexp(input=out_logits, dim=-1, keepdim=True)
logsumexp

tensor([[1.2711],
        [1.2375]])